DATA_ROOT: '../datasets/'
LOGS_ROOT: '../logs/'


MODEL:
  # architecture
  backbone: 'resnet50'
  generator: 'resnet_6blocks'
  pooling: 'gem'
  embed_feat: 0
  dropout: 0.

  dsbn: True

  sync_bn: True
  samples_per_bn: 16

  mean_net: False
  alpha: 0.999

  # pretraining
  imagenet_pretrained: False
  source_pretrained: '../logs/strong_baseline/model_best_veri.pth'
  G_pretrained: '../logs/duke/stage2/checkpoint_generator.pth'
  D_pretrained: '../logs/duke/stage2/checkpoint_discriminator.pth'
#  source_pretrained: null

DATA:

  height: 256
  width: 128
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]

  TRAIN:
    # augmentation
    is_autoaug: False

    is_flip: True
    flip_prob: 0.5

    is_pad: True
    pad_size: 10

    is_blur: False
    blur_prob: 0.5

    is_erase: True
    erase_prob: 0.5

    # dual augmentation for MMT
    is_mutual_transform: True
    mutual_times: 2


TRAIN:
  seed: 1
  deterministic: True
  # mixed precision training for PyTorch>=1.6
  amp: False
  stage: 3
  stage3_train_all: True

  # datasets
  datasets: {'veri': 'trainval',}
#  datasets: {'market1501': 'trainval', 'dukemtmcreid': 'trainval'}
  unsup_dataset_indexes: [0,]

  epochs: 20
  iters: 100

  LOSS:
    losses: {'hybrid_memory': 1.,'recon': 10., 'gan_D': 1., 'cross_entropy': 1., 'spcl':1.,
              'co':1.,'ad':1.}
    temp: 0.05
    momentum: 0.2

  # validate
  val_dataset: 'veri'
  val_freq: 1

  # sampler
  SAMPLER:
    num_instances: 4
    is_shuffle: True

  # data loader
  LOADER:
    samples_per_gpu: 32
    workers_per_gpu: 2

  # pseudo labels
  PSEUDO_LABELS:
    freq: 1 # epochs
    use_outliers: True
    norm_feat: True
    norm_center: True

    cluster: 'dbscan'
    eps: [0.58, 0.6, 0.62]
    min_samples: 4 # for dbscan
    dist_metric: 'jaccard'
    k1: 30 # for jaccard distance
    k2: 6 # for jaccard distance
    search_type: 0 # 0,1,2 for GPU, 3 for CPU (work for faiss)
    cluster_num: null

    # cluster: 'kmeans'
    # cluster_num: [500,]
    # dist_cuda: True

  # optim
  OPTIM:
    optim: 'adam'
    lr: 0.0001
    weight_decay: 0.0005

  OPTIM2:
    optim: 'sgd'
    lr: 0.00035
    weight_decay: 0.0005

  SCHEDULER:
    lr_scheduler: 'single_step'
    stepsize: 10
    gamma: 0.1


TEST:

  # datasets
  datasets: ['dukemtmcreid',]

  # data loader
  LOADER:
    samples_per_gpu: 32
    workers_per_gpu: 2

  # ranking setting
  dist_metric: 'euclidean'
  norm_feat: True
  dist_cuda: True

  # post processing
  rerank: False
  search_type: 0 # 0,1,2 for GPU, 3 for CPU (work for faiss)
  k1: 20
  k2: 6
  lambda_value: 0.3
